# Generated by Django 6.1.1 on 2026-09-18 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='unit_cost',
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name_raw',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
