# Generated by Django 6.1.1 on 2026-09-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_stockin_supplier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending Payment'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=20),
        ),
    ]
